//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticSearchSpec) DeepCopyInto(out *ElasticSearchSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticSearchSpec.
func (in *ElasticSearchSpec) DeepCopy() *ElasticSearchSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Growi) DeepCopyInto(out *Growi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Growi.
func (in *Growi) DeepCopy() *Growi {
	if in == nil {
		return nil
	}
	out := new(Growi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Growi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrowiAppSpec) DeepCopyInto(out *GrowiAppSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrowiAppSpec.
func (in *GrowiAppSpec) DeepCopy() *GrowiAppSpec {
	if in == nil {
		return nil
	}
	out := new(GrowiAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrowiList) DeepCopyInto(out *GrowiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Growi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrowiList.
func (in *GrowiList) DeepCopy() *GrowiList {
	if in == nil {
		return nil
	}
	out := new(GrowiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrowiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrowiSpec) DeepCopyInto(out *GrowiSpec) {
	*out = *in
	out.GrowiAppSpec = in.GrowiAppSpec
	out.MongoDBSpec = in.MongoDBSpec
	out.ElasticSearchSpec = in.ElasticSearchSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrowiSpec.
func (in *GrowiSpec) DeepCopy() *GrowiSpec {
	if in == nil {
		return nil
	}
	out := new(GrowiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrowiStatus) DeepCopyInto(out *GrowiStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GrowiAppStatus != nil {
		in, out := &in.GrowiAppStatus, &out.GrowiAppStatus
		*out = new(GrowiStatusType)
		**out = **in
	}
	if in.MongoDBStatus != nil {
		in, out := &in.MongoDBStatus, &out.MongoDBStatus
		*out = new(MongoDBStatusType)
		**out = **in
	}
	if in.ElasticSearchStatus != nil {
		in, out := &in.ElasticSearchStatus, &out.ElasticSearchStatus
		*out = new(ElasticSearchStatusType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrowiStatus.
func (in *GrowiStatus) DeepCopy() *GrowiStatus {
	if in == nil {
		return nil
	}
	out := new(GrowiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSpec) DeepCopyInto(out *MongoDBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSpec.
func (in *MongoDBSpec) DeepCopy() *MongoDBSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBSpec)
	in.DeepCopyInto(out)
	return out
}
