apiVersion: app.maeshinshin.github.io/v1
kind: Growi
metadata:
  labels:
    app.kubernetes.io/name: growi-manager
    app.kubernetes.io/managed-by: kustomize
  name: growi-sample
spec:
  growiappspec:
    version: "7.2.2"
    replicas: 1
  mongodbspec:
    version: "6.0"
    replicas: 2
  elasticsearchspec:
    version: "8.7.0"
    replicas: 1
  storageclass: standard
