apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "growi-manager.fullname" . }}-manager-role
  labels:
  {{- include "growi-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.maesh.dev
  resources:
  - growis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.maesh.dev
  resources:
  - growis/finalizers
  verbs:
  - update
- apiGroups:
  - apps.maesh.dev
  resources:
  - growis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "growi-manager.fullname" . }}-manager-rolebinding
  labels:
  {{- include "growi-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "growi-manager.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "growi-manager.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
