apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "growi-manager.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "growi-manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
