apiVersion: v1
kind: Service
metadata:
  name: {{ include "growi-manager.fullname" . }}-webhook-service
  labels:
  {{- include "growi-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: growi-manager
    control-plane: controller-manager
    {{- include "growi-manager.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
