name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - uses: ko-build/setup-ko@v0.9
        with:
          ko-version: '0.18.0'
      - id: ko-build
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        run: |
          ko build --bare --platform=all --tags latest,${{ github.ref_name }} cmd/main.go
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts-dir: charts
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

