name: Patch and Release

on:
  push:
    branches:
      - 'release-v*'

jobs:
  patch:
    name: Patch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup yq
        uses: mikefarah/yq@v4.44.2

      - name: Update installer.yaml
        run: |
          IMAGE_TAG=$(echo "${{ github.ref_name }}" | sed 's/^release-//')
          IMG="ghcr.io/maeshinshin/growi-manager:${IMAGE_TAG}" make build-installer

      - name: Update Chart and Values files
        run: |
          CHART_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^release-v//')
          IMAGE_TAG=$(echo "${{ github.ref_name }}" | sed 's/^release-//')

          yq e '.version = "'$CHART_VERSION'"' -i 'charts/growi-manager/Chart.yaml'
          yq e '.appVersion = "'$IMAGE_TAG'"' -i 'charts/growi-manager/Chart.yaml'
          IMG="ghcr.io/maeshinshin/growi-manager:${IMAGE_TAG}" make build-helmchart


      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          TAG=$(echo "${{ github.ref_name }}" | sed 's/^release-//')
          git add charts/growi-manager/Chart.yaml charts/growi-manager/values.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update chart version to ${{ github.ref_name }}"
            if git rev-parse $TAG >/dev/null 2>&1; then
              echo "Tag $TAG already exists."
            else
              git tag $TAG
              git push origin $TAG
              echo "✅ Created and pushed tag $TAG"
            fi
          fi
