name: E2E Tests

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix Flake
        run: nix flake check

      - name: Verify kind installation
        run: nix develop --command kind version

      - name: Create kind cluster
        run: nix develop --command kind create cluster

      - name: Running Test e2e
        run: |
          nix develop --command go mod tidy
          nix develop --command make test-e2e
