name: Tests

on:
  push:
  branches:
    - dev
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix Flake
        run: nix flake check

      - name: Running Tests
        run: |
          nix develop --command go mod tidy
          nix develop --command make test
